### ISSUE TITLE
Crossover Review Prisha Boreddy 4/5

### ISSUE THREAD

**Issue by anika1sharma1** [anika1sharma1/AnikaIndi#3]
CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [x] CB Create Task Coding requirements documented
- [x] Runtime of Code(with comments) on Replit/Intellij

Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [x] Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
- [x] Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
- [ ] Hack #1 Add Phone Number to Sign Up / Authorization screen
- [ ] Hack #2 Add logout to CRUD screen
- [ ] Hack #3 Add login_required to another portion of the project

**Comment by PrishaB** [comment]
Create task: 2/2
- Code is running 
- Writeup is also complete

Accounts and Logins Challenges/Hacks: 1/3
- started a new project and added everything to the project
- analysis was also done and flaws in security were properly discussed
- hacks aren't complete, code is there but not working for all hacks
